// countryFlags.ts — maps WeatherAPI country names to ISO-3166 alpha-2 codes
// so we can show a crisp SVG flag from flagcdn.com (one cached request, no
// runtime weight). Unknown names fall back to no flag (never breaks the UI).

const NAME_TO_ISO: Record<string, string> = {
  afghanistan: 'af',
  albania: 'al',
  algeria: 'dz',
  argentina: 'ar',
  armenia: 'am',
  australia: 'au',
  austria: 'at',
  azerbaijan: 'az',
  bahrain: 'bh',
  bangladesh: 'bd',
  belarus: 'by',
  belgium: 'be',
  bolivia: 'bo',
  'bosnia and herzegovina': 'ba',
  brazil: 'br',
  bulgaria: 'bg',
  cambodia: 'kh',
  cameroon: 'cm',
  canada: 'ca',
  chile: 'cl',
  china: 'cn',
  colombia: 'co',
  'costa rica': 'cr',
  croatia: 'hr',
  cuba: 'cu',
  cyprus: 'cy',
  czechia: 'cz',
  'czech republic': 'cz',
  denmark: 'dk',
  'dominican republic': 'do',
  ecuador: 'ec',
  egypt: 'eg',
  'el salvador': 'sv',
  estonia: 'ee',
  ethiopia: 'et',
  finland: 'fi',
  france: 'fr',
  georgia: 'ge',
  germany: 'de',
  ghana: 'gh',
  greece: 'gr',
  guatemala: 'gt',
  honduras: 'hn',
  'hong kong': 'hk',
  hungary: 'hu',
  iceland: 'is',
  india: 'in',
  indonesia: 'id',
  iran: 'ir',
  iraq: 'iq',
  ireland: 'ie',
  israel: 'il',
  italy: 'it',
  jamaica: 'jm',
  japan: 'jp',
  jordan: 'jo',
  kazakhstan: 'kz',
  kenya: 'ke',
  kuwait: 'kw',
  kyrgyzstan: 'kg',
  laos: 'la',
  latvia: 'lv',
  lebanon: 'lb',
  libya: 'ly',
  lithuania: 'lt',
  luxembourg: 'lu',
  macau: 'mo',
  madagascar: 'mg',
  malaysia: 'my',
  maldives: 'mv',
  malta: 'mt',
  mexico: 'mx',
  moldova: 'md',
  monaco: 'mc',
  mongolia: 'mn',
  montenegro: 'me',
  morocco: 'ma',
  myanmar: 'mm',
  nepal: 'np',
  netherlands: 'nl',
  'new zealand': 'nz',
  nicaragua: 'ni',
  nigeria: 'ng',
  'north macedonia': 'mk',
  macedonia: 'mk',
  norway: 'no',
  oman: 'om',
  pakistan: 'pk',
  panama: 'pa',
  paraguay: 'py',
  peru: 'pe',
  philippines: 'ph',
  poland: 'pl',
  portugal: 'pt',
  qatar: 'qa',
  romania: 'ro',
  russia: 'ru',
  'saudi arabia': 'sa',
  serbia: 'rs',
  singapore: 'sg',
  slovakia: 'sk',
  slovenia: 'si',
  'south africa': 'za',
  'south korea': 'kr',
  korea: 'kr',
  spain: 'es',
  'sri lanka': 'lk',
  sweden: 'se',
  switzerland: 'ch',
  taiwan: 'tw',
  tajikistan: 'tj',
  tanzania: 'tz',
  thailand: 'th',
  tunisia: 'tn',
  'trinidad and tobago': 'tt',
  turkey: 'tr',
  turkiye: 'tr',
  turkmenistan: 'tm',
  uganda: 'ug',
  ukraine: 'ua',
  'united arab emirates': 'ae',
  'united kingdom': 'gb',
  uk: 'gb',
  'united states of america': 'us',
  'united states': 'us',
  usa: 'us',
  uruguay: 'uy',
  uzbekistan: 'uz',
  venezuela: 've',
  vietnam: 'vn',
  yemen: 'ye',
  zambia: 'zm',
  zimbabwe: 'zw',
};

/** ISO-2 code for a WeatherAPI country name, or '' if unmapped. */
export function countryToIso(country: string): string {
  if (!country) return '';
  return NAME_TO_ISO[country.trim().toLowerCase()] ?? '';
}

/** Crisp SVG flag URL (single cached request), or '' if no known flag. */
export function flagUrl(country: string): string {
  const iso = countryToIso(country);
  return iso ? `https://flagcdn.com/${iso}.svg` : '';
}
